### ISSUE TITLE
Rewrite to MVVM architecture

### ISSUE THREAD

**Issue by Plastix** [Plastix/Kotlin-Android-Boilerplate#10]
I recently got a chance to use MVVM & Android Databinding in a project and I really like it. I like to think of MVVM has the evolution of MVP since the "presenter" (ViewModel) doesn't contain an instance of the View.

**Comment by ravidsrk** [comment]
@Plastix When are you planning to do this?

**Comment by Plastix** [comment]
@ravidsrk Some point this week.

**Comment by ravidsrk** [comment]
@Plastix Great, please create a separate repo for MVVM.

**Comment by Plastix** [comment]
@ravidsrk I was thinking of transitioning the master branch to MVVM and having a MVP branch.

**Comment by Plastix** [comment]
Ugh...As much as I love Kotlin I always run into issues trying to do fancy stuff with annotation processing tools.

I'm running into this KAPT limitation https://github.com/gen0083/KotlinDaggerDataBinding when trying to use types generated by annotation processors with Dagger (For example I want to be able to use one of my PaperParcel model classes in the dependency graph).

**Comment by Plastix** [comment]
🎉
