### ISSUE TITLE
Callback for when the presenter is available for use in the activity?

### ISSUE THREAD

**Issue by nimeetshah0** [Plastix/Kotlin-Android-Boilerplate#3]
I am trying to call my presenter method when the activity is created. But it fails because the presenter is not initialised. 

How do I handle situations like this? Is it a good idea to have a callback from PresenterActivity when the presenter is loaded? 

Thanks

EDIT: Turns out due to the Presenter Loader concept, the presenter will be available onResume() of the activity.

**Comment by Plastix** [comment]
For activities it is available in `onStart()` and in fragments it is available in `onResume()`

The callback you are looking for is `onPresenterProvided()` https://github.com/Plastix/Kotlin-Android-Boilerplate/blob/master/app/src/main/kotlin/io/github/plastix/kotlinboilerplate/ui/base/PresenterActivity.kt#L25

Don't forget to call super when overriding this callback!
