### ISSUE TITLE
Is this really using package by feature?

### ISSUE THREAD

**Issue by antonky** [Plastix/Kotlin-Android-Boilerplate#5]
In [this comment](https://www.reddit.com/r/androiddev/comments/4z6iid/i_finally_decided_to_give_kotlin_a_shot_here_is/d6tcaca) in your reddit post about this project, you said that this project is organized using the package by feature approach. I read the article that you linked to, and I think I sort of understand the idea. However, after examining the structure of your project, I couldn't really see any similarities to what was shown in the article. To be fair, I don't see any files called `model`, `presenter` or `view`, but, I do see `data` and `ui`, which sort of sounds like model and view to me. I'm not trying to judge or anything, just understand. I don't know if you'll agree with me, but I think [this](https://github.com/googlesamples/android-architecture/tree/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp) is a really good example of package by feature. Sorry if this came off as cynical or rude, it's definitley not my intention 😄. Hopefully you can shed some light on this for me 😆

**Comment by Plastix** [comment]
Good Question! The crux of package-by-feature is to place all feature specific classes into the same package. This way you don't have related classes spread all over your application.

`Model`/`Presenter`/`View` package structure is really package-by-layer! In this case, it is the separate layers of the MVP architecture pattern. While this may be fine for smaller applications, it can get really unwieldy when you have a lot of unrelated code in the same layer.

Say you want to delete feature `x`. If you use package-by-layer you would have to go into all the different layers to find files that are part of feature `x`. With package-by-feature, you immediately know to look at the `x` package to find the code. If you architect right, you get packages with high cohesion and modularity with low coupling between features.

I agree with you that the [googlesamples/android-architecture](https://github.com/googlesamples/android-architecture/tree/todo-mvp/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp) repo is a good example of package-by-feature. I've just taken the extra step of putting my screen specific packages into a root `ui` package (Note that the Google sample has the `statistics` screen package at the same level as the `data` package). 

My package structure is heavily inspired by [JakeWharton/u2020](https://github.com/JakeWharton/u2020). 

Hopefully this clears it up a little bit. 

You might want to check out my other Android app which uses the same package structure. It has a lot more screens so the [packaging of each screen/feature](https://github.com/Plastix/Forage/tree/master/app/src/main/java/io/github/plastix/forage/ui) is more apparent.

**Comment by antonky** [comment]
Ahh, that makes sense. Thanks a lot! 👍
