### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by jamolkhon** [Plastix/Kotlin-Android-Boilerplate#9]
* I think `ViewGroup.show()`/`ViewGroup.hide()` extension methods are redundant. `ViewGroup` is a `View`.
* `View.toggleVisibility()` would be a useful addition:
```
View.toggleVisibility() {
  visibility = if (visibility == View.VISIBLE) View.GONE else VIew.VISIBLE
}
```

Sorry, too lazy to make a PR currently.

**Comment by Plastix** [comment]
You are totally right. Thanks! 👍
